s0_vec: [0.0]
b_vec: [0.5]
target_Z: 5.0
continuity_correction_r: False
continuity_correction_rstar: True
out_pdf: "plots/paper_simple_pval_s0_b0p5.pdf"
out_significance_pdf: "plots/paper_simple_pval_s0_b0p5_sig.pdf"
significance_plots: True
individual_plots: False
ratio_plots: False
