s0_vec: [0.0]
b_vec: [1.0]
max_observed_count: 5
continuity_correction_r: False
continuity_correction_rstar: True
out_pdf: "paper/fig3_simple_pval_s0_b1.pdf"
out_significance_pdf: "paper/fig3_simple_significance_s0_b1.pdf"
significance_plots: True
individual_plots: False
ratio_plots: False
