s_vec: [2.0, 5.0, 10.0]
b_min: 0.1
b_max: 100.0
n_bpts: 50
n_outer: 5000
seed: 12345
continuity_correction_r: False
continuity_correction_rstar: True
mc_statistics: [median]
asimov_statistics: [r]
out_pdf: "paper/fig1_simple_asimov_bundle.pdf"
out_combined_pdf: "paper/fig1_simple_asimov.pdf"
individual_plots: False
