# pval_condor.sub
universe                = vanilla
executable              = run_pval.sh
arguments               = config.yaml $(Process)

output     = logs/pval_$(Process).out
error      = logs/pval_$(Process).err
log        = logs/pval_$(Process).log

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_executable     = YES
transfer_input_files    = pval.py, run_pval.sh, config.yaml

queue 1000
