# s_true = 10 : max_toys=1e7 (~213 s/exp, n_bpts=50). n_outer = 5 * 400 = 2000 (~18 min/job)
universe                = vanilla
executable              = run_pval.sh
arguments               = config_s10.yaml $(Process)

output     = logs/pval_s10_$(Process).out
error      = logs/pval_s10_$(Process).err
log        = logs/pval_s10_$(Process).log

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_executable     = YES
transfer_input_files    = pval.py, run_pval.sh, config_s10.yaml

request_cpus            = 1
request_memory          = 2048

queue 400
