# s_true = 5 : max_toys=1e7 (~190 s/exp, n_bpts=50). n_outer = 5 * 400 = 2000
universe                = vanilla
executable              = run_pval.sh
arguments               = config_s5.yaml $(Process)

output     = logs/pval_s5_$(Process).out
error      = logs/pval_s5_$(Process).err
log        = logs/pval_s5_$(Process).log

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_executable     = YES
transfer_input_files    = pval.py, run_pval.sh, config_s5.yaml

request_cpus            = 1
request_memory          = 2048

queue 400
