# Shared statistical utilities for counting experiments.

from .on import (
    poisson_tail,
    r_stat,
    r_stat as r_stat_on,
    q_stat,
    q_stat as q_stat_on,
    norm_survival,
    norm_survival as norm_survival_on,
    r_star as r_star_on,
    pvals_on,
    median_count,
    median_expected_significance,
)
from .on_off import (
    SQRT2,
    norm_survival as norm_survival_onoff,
    norm_isf,
    normal_sf,
    normal_isf,
    xlogy,
    b_profiled,
    loglik_diff,
    r_stat_onoff,
    r_signed,
    q_stat_onoff,
    q_value,
    r_star_onoff,
    r_star,
    sample_null_toys,
    required_toys_for_Z_precision,
    pvals_onoff,
    asimov_counts_onoff,
    asimov_Zs_onoff,
    expected_Z_mc_onoff,
    expected_significance_onoff,
)

__all__ = [
    # simple counting
    "poisson_tail",
    "r_stat",
    "r_stat_on",
    "q_stat",
    "q_stat_on",
    "norm_survival",
    "norm_survival_on",
    "r_star_on",
    "pvals_on",
    "median_count",
    "median_expected_significance",
    # on/off
    "SQRT2",
    "norm_survival_onoff",
    "norm_isf",
    "normal_sf",
    "normal_isf",
    "xlogy",
    "b_profiled",
    "loglik_diff",
    "r_stat_onoff",
    "r_signed",
    "q_stat_onoff",
    "q_value",
    "r_star_onoff",
    "r_star",
    "sample_null_toys",
    "required_toys_for_Z_precision",
    "pvals_onoff",
    "asimov_counts_onoff",
    "asimov_Zs_onoff",
    "expected_Z_mc_onoff",
    "expected_significance_onoff",
]
