# Shared statistical utilities for counting experiments.

from .common import discovery_pvalue, discovery_q0, discovery_z
from .on import (
    poisson_tail_on,
    r_stat_on,
    q_stat_on,
    norm_survival,
    norm_survival as norm_survival_on,
    r_star_on,
    pvals_on,
    median_expected_significance_on,
    expected_significance_on,
)
from .on_off import (
    norm_survival as norm_survival_onoff,
    xlogy,
    b_profiled,
    loglik_diff,
    r_stat_onoff,
    q_stat_onoff,
    r_star_onoff,
    sample_null_toys,
    required_toys_for_Z_precision,
    pvals_onoff,
    asimov_Zs_onoff,
    median_expected_significance_onoff,
    expected_significance_onoff,
)
from .lognormal import (
    background_lognormal,
    theta_profiled_lognormal,
    loglik_diff_lognormal,
    r_stat_lognormal,
    j_thetatheta_lognormal,
    q_stat_lognormal,
    r_star_lognormal,
    pvals_lognormal_numerical,
    asimov_Z_lognormal,
    median_expected_significance_lognormal,
    expected_significance_lognormal,
)

__all__ = [
    # discovery definition
    "discovery_z",
    "discovery_q0",
    "discovery_pvalue",
    # simple counting
    "poisson_tail_on",
    "r_stat_on",
    "q_stat_on",
    "norm_survival",
    "norm_survival_on",
    "r_star_on",
    "pvals_on",
    "median_expected_significance_on",
    "expected_significance_on",
    # on/off
    "norm_survival_onoff",
    "xlogy",
    "b_profiled",
    "loglik_diff",
    "r_stat_onoff",
    "q_stat_onoff",
    "r_star_onoff",
    "sample_null_toys",
    "required_toys_for_Z_precision",
    "pvals_onoff",
    "asimov_Zs_onoff",
    "median_expected_significance_onoff",
    "expected_significance_onoff",
    # log-normal constrained background
    "background_lognormal",
    "theta_profiled_lognormal",
    "loglik_diff_lognormal",
    "r_stat_lognormal",
    "j_thetatheta_lognormal",
    "q_stat_lognormal",
    "r_star_lognormal",
    "pvals_lognormal_numerical",
    "asimov_Z_lognormal",
    "median_expected_significance_lognormal",
    "expected_significance_lognormal",
]
